### ISSUE TITLE
Rotation Thrust can't be negative 

### ISSUE THREAD

**Issue by Synapse-labs-AI** [dominicdoty/lunar_lander#3]
Rotation thrust is clipped between 0 and 1, after reading the code, it seems that it a regression from new feature on thrust limit value
"snapToLimit"

**Comment by Synapse-labs-AI** [comment]
;)

**Comment by dominicdoty** [comment]
Looks like its time to start writing real tests... :sob:

**Comment by dominicdoty** [comment]
406e225 should fix this regression. Its deployed right now if you want to test it out to confirm before I close.

**Comment by Synapse-labs-AI** [comment]
This is OK ! Awesome ! :)
